import "@/app/globals.css";
import { LocaleProvider } from "@/components/i18n/locale-provider";
import Footer from "@/components/playground/footer";
import { Navbar } from "@/components/playground/navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {
  defaultLocal,
  getDictionary,
  hasLocale,
  Locale,
} from "../../lib/i18n/dictionaries";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }];
}

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  const { lang: initialLang } = await params;
  const lang: Locale = hasLocale(initialLang) ? initialLang : defaultLocal();
  const dict = await getDictionary(lang);
  return (
    <html lang={lang}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocaleProvider dict={dict}>
          <Navbar dict={dict} />
          {children}
          <Footer dict={dict} />
        </LocaleProvider>
      </body>
    </html>
  );
}
