import {
  TypographyH2,
  TypographyH3,
  TypographyP,
} from "@/components/ui/typography";
import { useTranslations } from "next-intl";

interface Props {}

export default function PrivacyPolicyPage({}: Props) {
  const t = useTranslations("privacyPolicy");

  return (
    <div className="flex flex-col items-center justify-between m-24">
      <h1 className="text-3xl font-semibold">{t("title")}</h1>

      <TypographyP>
        {t("lastUpdated", { updatedDate: new Date(2026, 0, 19) })}
      </TypographyP>
      <TypographyP>{t("summary")}</TypographyP>
      <TypographyH2>{t("interpretationsAndDefinitions.title")}</TypographyH2>
      <TypographyH3>
        {t("interpretationsAndDefinitions.interpretationSubtitle")}
      </TypographyH3>
      <TypographyP>
        {t("interpretationsAndDefinitions.interpretationDefinition")}
      </TypographyP>
      <TypographyH3>
        {t("interpretationsAndDefinitions.definitionsSubtitle")}
      </TypographyH3>
      <TypographyP>For the purposes of this Privacy Policy:</TypographyP>
      <ul>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.accountDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.affiliateDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.applicationDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.companyDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.countryDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.deviceDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            {t.rich("interpretationsAndDefinitions.personalDataDefinition", {
              strong: (chunks) => <strong>{chunks}</strong>,
            })}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>Service</strong> refers to the Application.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service or to assist the
            Company in analyzing how the Service is used.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </TypographyP>
        </li>
      </ul>
      <TypographyH2>Collecting and Using Your Personal Data</TypographyH2>
      <TypographyH3>Types of Data Collected</TypographyH3>
      <h4>Personal Data</h4>
      <TypographyP>
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </TypographyP>
      <ul>
        <li>
          <TypographyP>Email address</TypographyP>
        </li>
        <li>
          <TypographyP>First name and last name</TypographyP>
        </li>
        <li>
          <TypographyP>Usage Data</TypographyP>
        </li>
      </ul>
      <h4>Usage Data</h4>
      <TypographyP>
        Usage Data is collected automatically when using the Service.
      </TypographyP>
      <TypographyP>
        Usage Data may include information such as Your Device&apos;s Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </TypographyP>
      <TypographyP>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </TypographyP>
      <TypographyP>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </TypographyP>
      <h4>Information Collected while Using the Application</h4>
      <TypographyP>
        While using Our Application, in order to provide features of Our
        Application, We may collect, with Your prior permission:
      </TypographyP>
      <ul>
        <li>
          Pictures and other information from your Device&apos;s camera and
          photo library
        </li>
      </ul>
      <TypographyP>
        We use this information to provide features of Our Service, to improve
        and customize Our Service. The information may be uploaded to the
        Company&apos;s servers and/or a Service Provider&apos;s server or it may
        be simply stored on Your device.
      </TypographyP>
      <TypographyP>
        You can enable or disable access to this information at any time,
        through Your Device settings.
      </TypographyP>
      <TypographyH3>Use of Your Personal Data</TypographyH3>
      <TypographyP>
        The Company may use Personal Data for the following purposes:
      </TypographyP>
      <ul>
        <li>
          <TypographyP>
            <strong>To provide and maintain our Service</strong>, including to
            monitor the usage of our Service.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>To manage Your Account:</strong> to manage Your registration
            as a user of the Service. The Personal Data You provide can give You
            access to different functionalities of the Service that are
            available to You as a registered user.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>For the performance of a contract:</strong> the development,
            compliance and undertaking of the purchase contract for the
            products, items or services You have purchased or of any other
            contract with Us through the Service.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>To contact You:</strong> To contact You by email, telephone
            calls, SMS, or other equivalent forms of electronic communication,
            such as a mobile application&apos;s push notifications regarding
            updates or informative communications related to the
            functionalities, products or contracted services, including the
            security updates, when necessary or reasonable for their
            implementation.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>To provide You</strong> with news, special offers and
            general information about other goods, services and events which we
            offer that are similar to those that you have already purchased or
            enquired about unless You have opted not to receive such
            information.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>To manage Your requests:</strong> To attend and manage Your
            requests to Us.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>For business transfers:</strong> We may use Your information
            to evaluate or conduct a merger, divestiture, restructuring,
            reorganization, dissolution, or other sale or transfer of some or
            all of Our assets, whether as a going concern or as part of
            bankruptcy, liquidation, or similar proceeding, in which Personal
            Data held by Us about our Service users is among the assets
            transferred.
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>For other purposes</strong>: We may use Your information for
            other purposes, such as data analysis, identifying usage trends,
            determining the effectiveness of our promotional campaigns and to
            evaluate and improve our Service, products, services, marketing and
            your experience.
          </TypographyP>
        </li>
      </ul>
      <TypographyP>
        We may share Your personal information in the following situations:
      </TypographyP>
      <ul>
        <li>
          <strong>With Service Providers:</strong> We may share Your personal
          information with Service Providers to monitor and analyze the use of
          our Service, to contact You.
        </li>
        <li>
          <strong>For business transfers:</strong> We may share or transfer Your
          personal information in connection with, or during negotiations of,
          any merger, sale of Company assets, financing, or acquisition of all
          or a portion of Our business to another company.
        </li>
        <li>
          <strong>With Affiliates:</strong> We may share Your information with
          Our affiliates, in which case we will require those affiliates to
          honor this Privacy Policy. Affiliates include Our parent company and
          any other subsidiaries, joint venture partners or other companies that
          We control or that are under common control with Us.
        </li>
        <li>
          <strong>With business partners:</strong> We may share Your information
          with Our business partners to offer You certain products, services or
          promotions.
        </li>
        <li>
          <strong>With other users:</strong> when You share personal information
          or otherwise interact in the public areas with other users, such
          information may be viewed by all users and may be publicly distributed
          outside.
        </li>
        <li>
          <strong>With Your consent</strong>: We may disclose Your personal
          information for any other purpose with Your consent.
        </li>
      </ul>
      <TypographyP>
        We do not transfer or disclose your information to third parties for
        purposes other than the ones provided
      </TypographyP>
      <TypographyH3>Retention of Your Personal Data</TypographyH3>
      <TypographyP>
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations (for example, if we are required to retain your
        data to comply with applicable laws), resolve disputes, and enforce our
        legal agreements and policies.
      </TypographyP>
      <TypographyP>
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time, except
        when this data is used to strengthen the security or to improve the
        functionality of Our Service, or We are legally obligated to retain this
        data for longer time periods.
      </TypographyP>
      <TypographyH3>Transfer of Your Personal Data</TypographyH3>
      <TypographyP>
        Your information, including Personal Data, is processed at the
        Company&apos;s operating offices and in any other places where the
        parties involved in the processing are located. It means that this
        information may be transferred to — and maintained on — computers
        located outside of Your state, province, country or other governmental
        jurisdiction where the data protection laws may differ than those from
        Your jurisdiction.
      </TypographyP>
      <TypographyP>
        Your consent to this Privacy Policy followed by Your submission of such
        information represents Your agreement to that transfer.
      </TypographyP>
      <TypographyP>
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy and
        no transfer of Your Personal Data will take place to an organization or
        a country unless there are adequate controls in place including the
        security of Your data and other personal information.
      </TypographyP>
      <TypographyH3>Delete Your Personal Data</TypographyH3>
      <TypographyP>
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </TypographyP>
      <TypographyP>
        Our Service may give You the ability to delete certain information about
        You from within the Service.
      </TypographyP>
      <TypographyP>
        You may update, amend, or delete Your information at any time by signing
        in to Your Account, if you have one, and visiting the account settings
        section that allows you to manage Your personal information. You may
        also contact Us to request access to, correct, or delete any personal
        information that You have provided to Us.
      </TypographyP>
      <TypographyP>
        Please note, however, that We may need to retain certain information
        when we have a legal obligation or lawful basis to do so.
      </TypographyP>
      <TypographyH3>Disclosure of Your Personal Data</TypographyH3>
      <h4>Business Transactions</h4>
      <TypographyP>
        If the Company is involved in a merger, acquisition or asset sale, Your
        Personal Data may be transferred. We will provide notice before Your
        Personal Data is transferred and becomes subject to a different Privacy
        Policy.
      </TypographyP>
      <h4>Law enforcement</h4>
      <TypographyP>
        Under certain circumstances, the Company may be required to disclose
        Your Personal Data if required to do so by law or in response to valid
        requests by public authorities (e.g. a court or a government agency).
      </TypographyP>
      <h4>Other legal requirements</h4>
      <TypographyP>
        The Company may disclose Your Personal Data in the good faith belief
        that such action is necessary to:
      </TypographyP>
      <ul>
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>
          Prevent or investigate possible wrongdoing in connection with the
          Service
        </li>
        <li>
          Protect the personal safety of Users of the Service or the public
        </li>
        <li>Protect against legal liability</li>
      </ul>
      <TypographyH3>Security of Your Personal Data</TypographyH3>
      <TypographyP>
        The security of Your Personal Data is important to Us, but remember that
        no method of transmission over the Internet, or method of electronic
        storage is 100% secure. While We strive to use commercially acceptable
        means to protect Your Personal Data, We cannot guarantee its absolute
        security. If you would like to revoke access your data from Playground -
        be the best, please revoke our access to your data via the Google
        security settings page at{" "}
        <a
          href="https://security.google.com/settings"
          rel="external nofollow noopener"
          target="_blank"
        >
          https://security.google.com/settings
        </a>
      </TypographyP>
      <TypographyH2>
        Detailed Information on the Processing of Your Personal Data
      </TypographyH2>
      <TypographyP>
        The Service Providers We use may have access to Your Personal Data.
        These third-party vendors collect, store, use, process and transfer
        information about Your activity on Our Service in accordance with their
        Privacy Policies.
      </TypographyP>
      <TypographyH3>Usage, Performance and Miscellaneous</TypographyH3>
      <TypographyP>
        We use third-party Service Providers to maintain and improve our
        Service.
      </TypographyP>
      <ul>
        <li>
          <TypographyP>
            <strong>Youtube</strong>
          </TypographyP>
          <TypographyP>
            Their Privacy Policy can be viewed at{" "}
            <a
              href="https://www.youtube.com/t/terms"
              rel="external nofollow noopener"
              target="_blank"
            >
              https://www.youtube.com/t/terms
            </a>
          </TypographyP>
          <TypographyP>
            By using Playground - be the best you are agreeing to be in full
            compliance and bound with YouTube Terms of Service.
          </TypographyP>
          <TypographyP>
            Playground - be the best, the API Client, uses YouTube API
            Services{" "}
          </TypographyP>
        </li>
        <li>
          <TypographyP>
            <strong>Google</strong>
          </TypographyP>
          <TypographyP>
            Their Privacy Policy can be viewed at{" "}
            <a
              href="http://www.google.com/policies/privacy"
              rel="external nofollow noopener"
              target="_blank"
            >
              http://www.google.com/policies/privacy
            </a>
          </TypographyP>
        </li>
      </ul>
      <TypographyH2>Children&apos;s Privacy</TypographyH2>
      <TypographyP>
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13. If You are a parent or guardian and You are aware that
        Your child has provided Us with Personal Data, please contact Us. If We
        become aware that We have collected Personal Data from anyone under the
        age of 13 without verification of parental consent, We take steps to
        remove that information from Our servers.
      </TypographyP>
      <TypographyP>
        If We need to rely on consent as a legal basis for processing Your
        information and Your country requires consent from a parent, We may
        require Your parent&apos;s consent before We collect and use that
        information.
      </TypographyP>
      <TypographyH2>Links to Other Websites</TypographyH2>
      <TypographyP>
        Our Service may contain links to other websites that are not operated by
        Us. If You click on a third party link, You will be directed to that
        third party&apos;s site. We strongly advise You to review the Privacy
        Policy of every site You visit.
      </TypographyP>
      <TypographyP>
        We have no control over and assume no responsibility for the content,
        privacy policies or practices of any third party sites or services.
      </TypographyP>
      <TypographyH2>Changes to this Privacy Policy</TypographyH2>
      <TypographyP>
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </TypographyP>
      <TypographyP>
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective and update the &quot;Last
        updated&quot; date at the top of this Privacy Policy.
      </TypographyP>
      <TypographyP>
        You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are
        posted on this page.
      </TypographyP>
      <TypographyH2>Contact Us</TypographyH2>
      <TypographyP>
        If you have any questions about this Privacy Policy, You can contact us:
      </TypographyP>
      <ul>
        <li>By email: playgroundsocool@gmail.com</li>
      </ul>
    </div>
  );
}
